export const levelTitles = [
  { level: 1, title: "Bookworm" },
  { level: 2, title: "Page Turner" },
  { level: 3, title: "Story Seeker" },
  { level: 4, title: "Tale Collector" },
  { level: 5, title: "Chapter Chaser" },
  { level: 6, title: "Library Explorer" },
  { level: 7, title: "Literary Adept" },
  { level: 8, title: "Novel Navigator" },
  { level: 9, title: "Tome Keeper" },
  { level: 10, title: "Book Sage" },
  { level: 11, title: "Story Master" },
  { level: 12, title: "Epic Reader" },
  { level: 13, title: "Library Guardian" },
  { level: 14, title: "Literary Scholar" },
  { level: 15, title: "Wordsmith" },
  { level: 16, title: "Reading Virtuoso" },
  { level: 17, title: "Tale Weaver" },
  { level: 18, title: "Lore Keeper" },
  { level: 19, title: "Grand Bibliophile" },
  { level: 20, title: "Legend of Literature" },
];
